---
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/Users/renatadiaz/Documents/GitHub/weecology/LDA-kratplots")
knitr::opts_chunk$set(echo = TRUE)
```


```{r load packages and functions, include = F}
library(LDATS)
library(dplyr)
library(tidyr)
library(ggplot2)
source('functions/plots_from_ldats.R')
source('functions/lda_plot_function.R')
source('functions/convert_summary_to_dates.R')
```


```{r load lda, echo = F}
load('models/lda_c_and_e.Rdata')
```

## LDA model - with both control and exclosure plots


```{r plot both LDA,echo = F}
plot_lda_edited(selected, time_data$date, select_samples = NULL)


 plots = plot_community_composition_gg(community_composition(selected), c(1:selected@k), ylim = c(0, 1))
 
 plots
```



```{r load wts1, echo = F}
load('models/time_steps/ctrl_time_gran_wt1.Rdata')

rodent_data_ctrl = rodent_data
time_data_ctrl = time_data
changepoint_ctrl = changepoint
changepoint_models_ctrl = changepoint_models
selected_ctrl = selected

rm(rodent_data, time_data, changepoint, changepoint_models, selected)

load('models/time_steps/excl_time_gran_wt1.Rdata')

rodent_data_excl = rodent_data
time_data_excl = time_data
changepoint_excl = changepoint
changepoint_models_excl = changepoint_models
selected_excl = selected

rm(rodent_data, time_data, changepoint, changepoint_models, selected)

```

\newpage

#### Adjustments July 16

``` {r july 16, echo = F} 
load('models/lda_c_and_e2.Rdata')
```

LDA on both, plotting just *control* samples:

```{r plot control LDA, echo = F}
plot_lda_edited(selected, time_data$date, select_samples = which(rodent_data_all$plot_type == 'control'))
```



LDA on both, plotting just *exclosure* samples:



```{r plot ex LDA, echo = F}
plot_lda_edited(selected, time_data$date, select_samples = which(rodent_data_all$plot_type == 'exclosure'))
```
