---
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/Users/renatadiaz/Documents/GitHub/weecology/LDA-kratplots")
knitr::opts_chunk$set(echo = TRUE)
```


```{r load packages and functions, include = F}
library(LDATS)
library(dplyr)
library(tidyr)
library(ggplot2)
source('functions/plots_from_ldats.R')
source('functions/convert_summary_to_dates.R')
```

# With weights all equal

```{r load wts1, echo = F}
load('models/control_hg.Rdata')
```

## LDA models

#### Control plots LDA
```{r plot control LDA wt 1,echo = F, fig.height = 3.5, fig.width = 7}
plot_lda_edited(selected, time_data$date, select_samples = NULL)
```

## Changepoint models

#### Selected changepoint model for control plots

```{r cpt summary ctrl wt 1, echo = F}

ctrl_cpt_summary_dates <- convert_summary_to_dates(changepoint, time_data)

ctrl_cpt_summary_dates
```

```{r cpt plot ctrl wt 1, echo = F}

cps_gathered = tidyr::gather(as.data.frame(changepoint$cps), key = 'cpt', value = 'year_number', 1:changepoint$nchangepoints)

cps_years <- select(rodent_data, date) %>%
  mutate(date = format(as.Date(date, format="%d/%m/%Y"),'%Y')) %>%
  mutate(date = as.numeric(date)) %>%
  mutate(year_number = row_number()) 

cps_gathered <- left_join(cps_gathered, cps_years, by = 'year_number')

cps_hist <- ggplot(cps_gathered, aes(x=date, fill = cpt)) + 
  geom_histogram() +
  theme_bw() + 
  labs(title = 'Changepoint estimates - control')

cps_hist

cps <- cps_gathered %>%
  mutate(treatment = 'control')

```

#### Deviances for different numbers of changepoints - control
```{r ctrl wt 1 deviances, echo = F}

ctrl_deviances = list(NULL)

for(i in 1:length(changepoint_models)){
  ctrl_deviances[i] <- changepoint_models[[i]]$deviance
  names(ctrl_deviances)[i] <- changepoint_models[[i]]$nchangepoints
}


print(ctrl_deviances)

```

