---
title: "Results"
author: "Renata Diaz"
date: "5/30/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/Users/renatadiaz/Documents/GitHub/weecology/LDA-kratplots")
knitr::opts_chunk$set(echo = TRUE)

```


```{r load packages and functions, include = F}
library(LDATS)
library(dplyr)
source('functions/lda_plot_function.R')
```

## Exclosure plots

Granivores only, fewer plots (4), full time series.

```{r, eval = T}
load('models/excl_time_gran.Rdata')
```

LDA model:

```{r, echo = F}
plot(selected)
# 
# plots = plot_community_composition_gg(community_composition(selected), c(1:selected@k), ylim = c(0, 1))
# 
# plots
```


Changepoint model:

```{r, echo = F}
summarize_cps(changepoint$cps, prob = 0.95)

```

Here are some more diagnostics:

```{r, echo = F}

changepoint$MCMCdiagnostics

```

```{r plot exlosure cpt, echo = F}
library(ggplot2)
library(tidyr)

cps_gathered = tidyr::gather(as.data.frame(changepoint$cps), key = 'cpt', value = 'year_number', 1:2)

cps_years <- select(rodent_data, date) %>%
  mutate(date = format(as.Date(date, format="%d/%m/%Y"),'%Y')) %>%
  mutate(date = as.numeric(date)) %>%
  mutate(year_number = row_number()) 

cps_gathered <- left_join(cps_gathered, cps_years, by = 'year_number')

cps_hist <- ggplot(cps_gathered, aes(x=date, fill = cpt)) + 
  geom_histogram() +
  theme_bw() + 
  labs(title = 'Changepoint estimates - exclosures')

cps_hist

cps_exclosures <- cps_gathered %>%
  mutate(treatment = 'exclosure')

```

\newpage

## Control plots

Granivores only, fewer plots (4), full time series.

```{r, eval = T}
load('models/ctrl_time_gran.Rdata')
```

LDA model:

```{r, echo = F}
plot(selected)
# 
# plots = plot_community_composition_gg(community_composition(selected), c(1:selected@k), ylim = c(0, 1))
# 
# plots
```


Changepoint model:

```{r, echo = F}
summarize_cps(changepoint$cps, prob = 0.95)

```


Here are some more diagnostics:

```{r, echo = F}

changepoint$MCMCdiagnostics

```

```{r plot control cpt, echo = F}

cps_gathered = tidyr::gather(as.data.frame(changepoint$cps), key = 'cpt', value = 'year_number', 1:2)

cps_years <- select(rodent_data, date) %>%
  mutate(date = format(as.Date(date, format="%d/%m/%Y"),'%Y')) %>%
  mutate(date = as.numeric(date)) %>%
  mutate(year_number = row_number()) 

cps_gathered <- left_join(cps_gathered, cps_years, by = 'year_number')

cps_hist <- ggplot(cps_gathered, aes(x=date, fill = cpt)) + 
  geom_histogram() +
  theme_bw() + 
  labs(title = 'Changepoint estimates - controls')

cps_hist

```
\newpage
```{r plot both cpts, echo = F}
cps_joint = cps_gathered %>%
  mutate(treatment = 'control') %>%
  bind_rows(cps_exclosures)



cps_joint_hist <- ggplot(cps_joint, aes(x=date, fill = treatment)) + 
  geom_histogram(binwidth =1) +
  theme_bw() + 
  labs(title = 'Changepoint estimates')

cps_joint_hist

```

